// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlpOqVDSWLtJG8eIZi9iT5azP9iSvhU1Q',
    appId: '1:101994831800:web:ceeeb40758d06c24d4394d',
    messagingSenderId: '101994831800',
    projectId: 'credit-card-manager-44254',
    authDomain: 'credit-card-manager-44254.firebaseapp.com',
    storageBucket: 'credit-card-manager-44254.firebasestorage.app',
    measurementId: 'G-CCF9N6BDGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Iu4XeEQwngu7_qXOqRBjE5yk1F73C90',
    appId: '1:101994831800:android:00438b8adac9b810d4394d',
    messagingSenderId: '101994831800',
    projectId: 'credit-card-manager-44254',
    storageBucket: 'credit-card-manager-44254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2KtJlLHxt661_Hf2bpgdppr3AaGphqg4',
    appId: '1:101994831800:ios:0fb4391a8d67ee28d4394d',
    messagingSenderId: '101994831800',
    projectId: 'credit-card-manager-44254',
    storageBucket: 'credit-card-manager-44254.firebasestorage.app',
    iosBundleId: 'com.example.creditcardmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2KtJlLHxt661_Hf2bpgdppr3AaGphqg4',
    appId: '1:101994831800:ios:0fb4391a8d67ee28d4394d',
    messagingSenderId: '101994831800',
    projectId: 'credit-card-manager-44254',
    storageBucket: 'credit-card-manager-44254.firebasestorage.app',
    iosBundleId: 'com.example.creditcardmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlpOqVDSWLtJG8eIZi9iT5azP9iSvhU1Q',
    appId: '1:101994831800:web:39431757d0f56803d4394d',
    messagingSenderId: '101994831800',
    projectId: 'credit-card-manager-44254',
    authDomain: 'credit-card-manager-44254.firebaseapp.com',
    storageBucket: 'credit-card-manager-44254.firebasestorage.app',
    measurementId: 'G-FY3Z1YS2KP',
  );
}
